### ISSUE TITLE
RootDSE

### ISSUE THREAD

**Issue by vletoux** [Mr-Un1k0d3r/RedTeamCSharpScripts#1]
Just in case you didn’t know, you can get the current domain name in LDAP using the rootDSe and then making the domain argument optional:
https://docs.microsoft.com/en-us/windows/win32/ad/example-code-for-getting-the-distinguished-name-of-the-domain

**Comment by Mr-Un1k0d3r** [comment]
Sorry for the late response never got the notification. Indeed I can auto discover it but I usually deal with infrastructure that have multiple trust so providing the domain is important. I can definitively add the auto discovery feature and make the domain an option.
